[package]
name = "juno_client"
version = "0.1.0"
authors = ["Jon Grimes <jong@spiceworks.com>"]

[dependencies]
toml = "0.4"
tokio = "0.1.7"
hyper = "0.12"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.6", features = ["v4"] }
libc = "0.2"